### PR TITLE
feat: add babel transform es6 to es5

### PR DESCRIPTION
**Pull request by zxf4399**
I want to use es5 code because of ie11. Please merge it, thanks. @nfriedly

### CODE REVIEW

**Comment by nfriedly** [comment]
Hey @zxf4399,

I'm not necessarily against this, but can you describe your use-case? Typically in browsers you don't need to read set-cookie headers because the browser does that for you - you can just make the request and then check `document.cookie` for the cookie value.

**Comment by zxf4399** [comment]
Hey @nfriedly ,
I am a front-end developer and now i use [next.js](https://github.com/vercel/next.js). I want to set cookies in a best way, so I choose [nookies](https://github.com/maticzav/nookies). `nookies` depend on your project  `set-cookie-parser`, So I add babel support `ie11`

**Comment by nfriedly** [comment]
Would you be willing to try a couple of other things first?

1) Try configuring your babel instance to tranapile this module. See  https://nextjs.org/docs/advanced-features/customizing-babel-config and https://stackoverflow.com/a/56428646/933879 and https://babeljs.io/docs/en/options
 
2) Configure We pack to omit the set-cookie-parser module from browser bundles. I'm pretty sure this is possible, but I'm not finding any examples of it right now.

3) only import the `setCookie` function in server-side code

Also, I'm wondering if @maticzav has any ideas or suggestions?

**Comment by zxf4399** [comment]
Hey @nfriedly ,

I think `nookies` [support older browsers](https://github.com/maticzav/nookies/issues/52), we should also support it too

**Comment by nfriedly** [comment]
Ok, I came up with a simpler solution. There was literally only one line of code that used an ES6 feature (template string for an error message), so I just re-wrote it to use string concatenation and changed the lintier back to ES5. The fix will be published in v2.4.8 shortly.

Thank you for bring it to my attention and for doing to work to get transpiration set up. I'm sorry we're not using that work, but I do think that this is a better solution.

Also sorry I broke things in a patch release; I hadn't realized anyone was using this library in a way that would see it shipped to browsers. (There's probably a potential improvement to nookies there to decrease the JS bundle size, since it's not actually using this code in browsers.)

**Pull request closed without merging**
